### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by Ijaiswalshivam** [Ijaiswalshivam/Talk-In#10]

**Comment by Verma-Sumit** [comment]
please assign me this

**Comment by Ijaiswalshivam** [comment]
> please assign me this

@Verma-Sumit Assigned

**Comment by Verma-Sumit** [comment]
Sir, as I am a beginner in Github & open source, can you please guide me some basic things?
How to contribute in this issue?

**Comment by Ijaiswalshivam** [comment]
Refer this: https://www.freecodecamp.org/news/how-to-make-your-first-pull-request-on-github-3/

**Comment by Aditya19110** [comment]
Can you also assign me the task please

**Comment by X-Cypher** [comment]
Hi, i am interested to contribute. Can you assign this issue to me

**Comment by Ijaiswalshivam** [comment]
@Aditya19110 Assigned

**Comment by Aditya19110** [comment]
SO i ahve to create a documentation on what? @Ijaiswalshivam Like can you add some description about the task
