### ISSUE TITLE
Adding the Group Button and attaching it to Activity.

### ISSUE THREAD

**Issue by Qomfortzone** [Ijaiswalshivam/Talk-In#105]
@Ijaiswalshivam 
Assign me this.

**Comment by Ijaiswalshivam** [comment]
@Qomfortzone assigning you #issue9

**Comment by Qomfortzone** [comment]
Okay !

**Comment by Ijaiswalshivam** [comment]
@Qomfortzone plz comment over there so that i can assign you.

**Comment by Ijaiswalshivam** [comment]
@Qomfortzone I'm reopening this issue again, please fork it again after that add the additional feature
