### ISSUE TITLE
Chat Screen

### ISSUE THREAD

**Issue by Lucky-chelani** [Ijaiswalshivam/Talk-In#106]
I would try to make some changes in chat screen under Ggsoc'24

**Comment by Ijaiswalshivam** [comment]
@Lucky-chelani assigned

**Comment by Lucky-chelani** [comment]
please specify the level

**Comment by Ijaiswalshivam** [comment]
@Lucky-chelani as per the change/contribution I'll level it.

**Comment by Qomfortzone** [comment]
I am adding a Fragment instead of Activity for the Chat Screen so wait  i will push it an hour then start working on it

**Comment by Lucky-chelani** [comment]
please check it

**Comment by Ijaiswalshivam** [comment]
@Lucky-chelani kindly create pull req.

**Comment by Lucky-chelani** [comment]
yah i done and you merged it also
