### ISSUE TITLE
Error: There are some issues with build.gradle file

### ISSUE THREAD

**Issue by maniyaom** [Ijaiswalshivam/Talk-In#111]
**Description:**
Some plugins are duplicated

**Comment by maniyaom** [comment]
@Ijaiswalshivam please assign me.

**Comment by Qomfortzone** [comment]
Contributors please run the app on device one before pushing the code !!!

**Comment by Ijaiswalshivam** [comment]
@maniyaom still it is same.

**Comment by maniyaom** [comment]
@Ijaiswalshivam it is because of another xml file this is not gradle issue.
