### ISSUE TITLE
Messaging feature between users in the Web App

### ISSUE THREAD

**Issue by SatwikMohan** [Ijaiswalshivam/Talk-In#120]
**Description:**
The feature will allow the user to message and chat among friends.

**Problem:**
The feature does not solve a problem but adds a functionality

**Proposed Solution:**
The user can send message to another using the application by clicking on that particular user. The user can send and receive messages.

**Steps for Implementation:**
1. Creating a message screen or chat screen
2. Step two...
   - send a message to the selected user under a sender id and receive a message under the receiver id.
3. The feature will be implemented using flutter and the feature can be implemented using external packages like chat bubble provided by flutter_chatbubble.

**Additional Context:**
I am a contributor and I would like to work on the issue.

**Comment by Ijaiswalshivam** [comment]
@SatwikMohan assigned. 
Also can you please tell us how we can deploy it?

**Comment by SatwikMohan** [comment]
@Ijaiswalshivam   Thankyou for assigning. The website can be deployed using firebase hosting.

**Comment by Ijaiswalshivam** [comment]
Can you please tell us the procedure?
Or you can update in the readme.md file

**Comment by SatwikMohan** [comment]
@Ijaiswalshivam  Sure I will update the readme.md file.
