### ISSUE TITLE
Sign Up and Sign In page is not working properly

### ISSUE THREAD

**Issue by maniyaom** [Ijaiswalshivam/Talk-In#121]
**Description:**
When we try to sign in it says verify your email address. In Signup page email is registered on firebase but there is a problem while saving user data to firestore

**Comment by maniyaom** [comment]
@Ijaiswalshivam For Sign in issue i have the solution but for signup do you want to use firebase database or go with firestore?

**Comment by Ijaiswalshivam** [comment]
Currently it assigned to someone else...
But it is not solved within 2 days then i will assign you

**Comment by Ijaiswalshivam** [comment]
Currently it assigned to someone else...
But it is not solved within 2 days then i will assign you and i want to use firebase

**Comment by Ijaiswalshivam** [comment]
Btw you can work on main activity for user interface modification

**Comment by Ijaiswalshivam** [comment]
@maniyaom still when i'm signing up with new mail address it shows "The email address is already in use by another account" after that when i am signing in with same mail id then it is sending the verification, so please fix it, that is when user sign up then he/she receives verification mail, and at sign in page no verification is required if signing in with registered mail .

**Comment by Ijaiswalshivam** [comment]
@NitinSigilipelli whatever required file will be, I'll put it over there.

**Comment by maniyaom** [comment]
> @maniyaom still when i'm signing up with new mail address it shows "The email address is already in use by another account" after that when i am signing in with same mail id then it is sending the verification, so please fix it, i.e; when user sign up then he/she receives verification mail, and at sign in page no verification is required if signing in with registered mail .

@Ijaiswalshivam I have fixed signup page problem now you can check that.
and for signin page : If user missed to verify their mail id on sign up page then user will be able to verify the mail on sign in page. That's why i have put verification at signin page.  still If you don't want to add verification on sign in page, I will remove it.

**Comment by Ijaiswalshivam** [comment]
@maniyaom additional requirement of verification at sign in page doesn't seems to be look flexible so better remove it.

**Comment by Ijaiswalshivam** [comment]
> @maniyaom additional requirement of verification at sign in page doesn't seems to be look flexible so better remove it. 

And also in previous pr, new users mail were only authenticated but there profile can't be seen by other users i.e; no additional profile is were built
