### ISSUE TITLE
Export Code

### ISSUE THREAD

**Issue by Qomfortzone** [Ijaiswalshivam/Talk-In#125]
After #124 Pull Request gets merged.
Export the Chat List Activity code to Chat Fragment.
Export User Profile(Logout feature) code to Profile Fragment.
Connect the Recycler view Properly.

Anyone who can do this **ASAP** comment below.
@Ijaiswalshivam Make this done to make futher pushes.

**Comment by maniyaom** [comment]
all the users are not visible on chat list activity. I will fix that

**Comment by Ijaiswalshivam** [comment]
@maniyaom assigned

**Comment by Ijaiswalshivam** [comment]
@Qomfortzone if you could look over it then it would be better as you have changed many files so it's difficult to organize all.

**Comment by Qomfortzone** [comment]
@Ijaiswalshivam Okay I'll see it tonight.
