### ISSUE TITLE
login/signup

### ISSUE THREAD

**Issue by Ijaiswalshivam** [Ijaiswalshivam/Talk-In#134]
*Description:*
verification mail not received on registered mail

*Current Behavior:*
sign up page show "this mail is already use by another account"
and sign in page only toast a message "verify your mail first" but mail not received"

*Expected Behavior:*
at very first signup when user register then only verification is required, but not at login and if user login without verifying it then reject that process.

**Comment by maniyaom** [comment]
@Ijaiswalshivam why are you trying to use firestore in signup page. this is causing error --> sign up page show "this mail is already use by another account"

**Comment by maniyaom** [comment]
@Ijaiswalshivam and due to previous commit one more problem is there. if you signup using new mail id and then without verifying email if you try to sign in and one toast shows that email is not verified but if you press back button then you will get logged in

**Comment by maniyaom** [comment]
i can fix this please assign me

**Comment by Ijaiswalshivam** [comment]
> @Ijaiswalshivam and due to previous commit one more problem is there. if you signup using new mail id and then without verifying email if you try to sign in and one toast shows that email is not verified but if you press back button then you will get logged in

yes it is happening.

**Comment by Ijaiswalshivam** [comment]
@maniyaom assigned
