### ISSUE TITLE
Adding the Search User Activity 

### ISSUE THREAD

**Issue by Qomfortzone** [Ijaiswalshivam/Talk-In#135]
Searching user by usernames
Fixing the previous bug

@Ijaiswalshivam Assign me this.

**Comment by Ijaiswalshivam** [comment]
@Qomfortzone firstly fix issue #105 after that i'm assigning this to you.

**Comment by Ijaiswalshivam** [comment]
@Qomfortzone can you please refork it and then implement these feature, as from now login and signup feature is fully functional

**Comment by Ijaiswalshivam** [comment]
And why not search button on top of the bar?

**Comment by Qomfortzone** [comment]
@Ijaiswalshivam 
It becomes more easy to reach there ... It can be improved later ..wherever you want to place it...According to me it is perfectly fine there...some style adjustments can be made....

I will fork again and implement everything in a single commit.

**Comment by Ijaiswalshivam** [comment]
Hmm ok
