### ISSUE TITLE
Reduce message gap between send and receive one

### ISSUE THREAD

**Issue by Ijaiswalshivam** [Ijaiswalshivam/Talk-In#138]
![WhatsApp Image 2024-05-17 at 14 38 19_006a814c](https://github.com/Ijaiswalshivam/Talk-In/assets/94839938/01512a2e-807f-4d9b-ac3d-b32097bb8358)

**Comment by hdhimalay** [comment]
assign this to me

**Comment by Ijaiswalshivam** [comment]
@hdhimalay assigned
