### ISSUE TITLE
Add UI Fixes such as Progress Bar in Web APP

### ISSUE THREAD

**Issue by SatwikMohan** [Ijaiswalshivam/Talk-In#140]
**Description:**
The web app will have some UI fixes which will make the app more user friendly. The changes will also involve adding of view models.

**Problem:**
The app lacks user convenience.

**Proposed Solution:**
The app will become efficient and user friendly.

**Steps for Implementation:**
1. Adding progress bar during login/signup
2. Step two...
   - Adding progress during loading data
3. Adding UI changes while accepting and sending requests.

**Additional Context:**
I am GSSOC'24 contributor and would like to contribute to the issue.

**Comment by DebojitDas2003** [comment]
Please assign this issue to me.
