### ISSUE TITLE
Adding Auto-commenting feature on PR merged

### ISSUE THREAD

**Issue by Sambit-Mondal** [Ijaiswalshivam/Talk-In#141]
**Description:**
To enhance our communication and acknowledgment process, I want to implement an auto-commenting feature for Pull Requests within the project repository.

**Problem:**
- When pull requests (PRs) are merged in a project, it is often important to provide consistent feedback or notifications to the contributors. 
- Currently, this process can be manual and time-consuming, leading to inconsistent communication and delayed acknowledgments. 
- This can frustrate both maintainers, who have to remember to comment, and contributors, who might feel their efforts are not promptly recognized.

**Proposed Solution:**
- This feature will automatically generate comments under the following circumstances:
- PR Merged: Upon the successful merging of a pull request (PR), an auto-comment will be added to the corresponding issue, indicating that the PR has been merged and expressing gratitude to the contributor for their valuable contribution

**Additional Context:**
- This feature aims to solve the problem of inconsistent and delayed communication following the merging of PRs. 
- By automating the commenting process, it ensures that contributors receive timely feedback and acknowledgments. It also reduces the administrative burden on maintainers, allowing them to focus more on code reviews and other critical tasks.

**Comment by Ijaiswalshivam** [comment]
@Sambit-Mondal Good to know that you want to contribute on this project, but currently these enhancements are not required, btw we welcome you to contribute on other listed issue under GSsoc'24.
