### ISSUE TITLE
Adding Auto-commenting feature for PR raised

### ISSUE THREAD

**Issue by Sambit-Mondal** [Ijaiswalshivam/Talk-In#143]
**Description:**
This feature introduces a new GitHub Actions workflow that automatically comments on new and updated pull requests. 

**Problem:**
- When contributors raise pull requests (PRs) in a project, it is crucial to provide immediate acknowledgment and feedback to encourage collaboration and maintain transparency. 
- However, manually commenting on every PR can be time-consuming for maintainers, leading to delays and inconsistency in communication. This can result in contributors feeling undervalued or discouraged from further participation.

**Proposed Solution:**
- This feature aims to streamline the contribution process by providing contributors with immediate feedback and guidance upon creating or updating their pull requests.
- This feature aims to address the problem of delayed and inconsistent communication following the raising of PRs.

**Additional Context:**
- By automatically commenting on PRs as soon as they are raised, it ensures that contributors receive immediate feedback and acknowledgment for their efforts. 
- This fosters a positive and supportive environment for collaboration, encouraging continued participation and engagement from contributors.

**Comment by Ijaiswalshivam** [comment]
@Sambit-Mondal Good to know that you want to contribute on this project, but currently these enhancements are not required, btw we welcome you to contribute on other listed issue under GSsoc'24.
