### ISSUE TITLE
Description: Refactoring findviewbyid to Viewbinding in whole application

### ISSUE THREAD

**Issue by Pranishkafle6175** [Ijaiswalshivam/Talk-In#150]
**Description:**
Refactoring findviewbyid to ViewBinding in Whole appliaction

**Problem:**
The code is messier and unstructured this makes the project complicated and outdated.

**Proposed Solution:**
I will enable viewbinding and change all the findviewbyid in the application so that the code is less messier.

**Comment by Pranishkafle6175** [comment]
Assign me!!

**Comment by Adya-04** [comment]
Please assign me!

**Comment by javaman97** [comment]
@Pranishkafle6175  What's the progress ?

**Comment by Pranishkafle6175** [comment]
I will initiate the pull request by tomorrow evening!
