### ISSUE TITLE
docs: pull_reuest_template.md template file is  not working

### ISSUE THREAD

**Issue by officeneerajsaini** [Ijaiswalshivam/Talk-In#151]
**Description:**
PR Template is not working 

**Expected Behavior:**
Pr Template should be working

**Actual Behavior:**
when someone raising pr it will go trough pr template 

**Additional Context:**
it's not working because it's inside ISSUE_TEMPLATE directory it should be inside .github/ directory .

**Comment by suhanipaliwal** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by officeneerajsaini** [comment]
@Ijaiswalshivam , I'd like to work on this issue under GSSOC. Could you please add the necessary label and tag to the issue and assign it to me?

**Comment by officeneerajsaini** [comment]
@Ijaiswalshivam , I'd like to work on this issue under GSSOC. Could you please add the necessary label and tag to the issue and assign it to me?

**Comment by Ijaiswalshivam** [comment]
@officeneerajsaini @suhanipaliwal currently it is not required for this project.
