### ISSUE TITLE
Settings Tab in Web App

### ISSUE THREAD

**Issue by SatwikMohan** [Ijaiswalshivam/Talk-In#153]
**Description:**
The settings tab will allow the user to change profile pic, name and will allow to add about or description of oneself.

**Problem:**
It will give the freedom to interact more on the platform by using beautiful profile pictures and about.

**Proposed Solution:**
The user will go to settings tab and will be provided with edit buttons. By using those edit button user can update the database according to the information provided. **The setting tab will also contain the functionality to allow the profile picture visible to only friends which can be turned on or off.**

**Steps for Implementation:**
1. Select the settings tab and open the settings screen
2. Then user will select the profile detail to be updated
3. Upload the information accordingly and will update the database where media will be stored in firebase storage.

**Additional Context:**
I am a GSSOC'24 contributor and would like to work on the issue.

**Comment by Ijaiswalshivam** [comment]
@SatwikMohan assigned
