### ISSUE TITLE
The outlined textbox for entering mobile number is glitchy

### ISSUE THREAD

**Issue by DebojitDas2003** [Ijaiswalshivam/Talk-In#154]
**Description:**
The outlined textbox for entering a mobile number on the signup page is not a properly outlined textbox. It's just a textbox over a rectangular box. Also, GET OTP button is not properly aligned. 

**Expected Behavior:**
The Get OTP button should be aligned with the outlined textbox.
The textbox should be a outlined textbox.
The GET OTP button should introduce another outlined textbox to insert the otp.

**Actual Behavior:**
The textbox is a normal textbox created on a rectangular outlined box.
Upon pressing the GET OTP button it is not working

**Added Context:**
I am a GSSOC'24 contributor. I can fix this issue. Please assign it to me.

![Screenshot 2024-05-19 014101](https://github.com/Ijaiswalshivam/Talk-In/assets/119345941/75c019b8-ec88-4e9a-8b2c-0b1032c0fb11)

**Comment by Ijaiswalshivam** [comment]
@DebojitDas2003 currently it is under another contributor with same issue.
