### ISSUE TITLE
Offline Mode: Implementation in this app

### ISSUE THREAD

**Issue by anushka-cseatmnc** [Ijaiswalshivam/Talk-In#16]
**Describe the solution you'd like**
I propose implementing an offline mode feature for the Talk-In text messaging chat app developed using Kotlin. This feature will allow users to read and compose messages even without an internet connection, ensuring uninterrupted communication.

**Feature problem and its solution**
The problem this feature aims to solve is the limitation users face when they are unable to access the internet but still wish to interact with the chat app. In scenarios such as poor network coverage or temporary loss of connectivity, users are often left unable to read incoming messages or compose new ones, leading to a disjointed communication experience.

By introducing an offline mode, users will have the ability to continue using the app seamlessly, regardless of their internet connection status. They can compose messages offline, which will be saved locally on their device, and once an internet connection is restored, these messages will be sent automatically. Similarly, users will be able to view incoming messages even when offline, ensuring they stay updated on conversations even in the absence of an internet connection.

**Additional context**
Implementing an offline mode will greatly enhance the user experience of the Talk-In app, making it more robust and reliable. Users will appreciate the ability to stay connected with their contacts, regardless of their internet connectivity status. Additionally, this feature aligns with the app's goal of providing a convenient and user-friendly messaging experience. --Gssoc'24

**Comment by Vishwajith-Shettigar** [comment]
`users will be able to view incoming messages even when offline, ensuring they stay updated on conversations even in the absence of an internet connection`.

How users will be able to view incoming messaged in offline ?

**Comment by Ijaiswalshivam** [comment]
@anushka-cseatmnc assigned
