### ISSUE TITLE
Google, Facebook, Twitter and Yahoo Authentication in Web App

### ISSUE THREAD

**Issue by SatwikMohan** [Ijaiswalshivam/Talk-In#166]
**Description:**
The user can connect using Google . Facebook , Twitter or Yahoo signin.

**Problem:**
It will give user more options to get connected with TalkIn.

**Proposed Solution:**
The authentication will be implemented using Firebase Authentication.

**Steps for Implementation:**
1. The user will be able to select an authentication method from the options given
2. The user on clicking on a signin method get registered using the auth credential received on invoking a signin method.

**Additional Context:**
I am a GSSOC'24 contributor and would like to work on the issue.

**Comment by SatwikMohan** [comment]
Hello @Ijaiswalshivam 
I have setup the google authentication but for rest of the authentications I need to create developer account where I have to register the application to get app_id and secrets to register the provider in Firebase.

**Comment by Ijaiswalshivam** [comment]
Tell me your mail id, I'll give you the access to know the details regarding firebase..

**Comment by SatwikMohan** [comment]
@Ijaiswalshivam  satwikmohan18@gmail.com

Actually The id and secrets are not in the firebase project but they have to be generated by creating developer accounts for facebook , twitter and yahoo separately and we need to register the app in those accounts to get id and secrets which we will pass in the firebase project to add provider.
