### ISSUE TITLE
Add toggle button For location on/off in profile screen 

### ISSUE THREAD

**Issue by Ijaiswalshivam** [Ijaiswalshivam/Talk-In#172]

**Comment by maniyaom** [comment]
@Ijaiswalshivam assign me

**Comment by Ijaiswalshivam** [comment]
@maniyaom ASSIGNED

**Comment by Akshaykomar890** [comment]
hello @Ijaiswalshivam can you assign it to me ?

**Comment by maniyaom** [comment]
I will do it by today afternoon only please wait...

**Comment by maniyaom** [comment]
@Ijaiswalshivam If I add toggle button then I have to save the state of that in database. But users who will signup now onwards only they will have this value. Is it ok?

**Comment by Ijaiswalshivam** [comment]
Yeah... Sure.. I'll manage previous database.

**Comment by maniyaom** [comment]
@Ijaiswalshivam I have raised PR and also in database for every user showLocation=false is also added
