### ISSUE TITLE
[Feature Request]: Show timestamps for each message to indicate when it was sent.

### ISSUE THREAD

**Issue by Vishwajith-Shettigar** [Ijaiswalshivam/Talk-In#18]
**Feature problem and its solution**

Message Timestamps: Show timestamps for each message to indicate when it was sent.

**Comment by Vishwajith-Shettigar** [comment]
Hi @Ijaiswalshivam, can you please assign this issue to me ? i would like to work on this.

**Comment by Vishwajith-Shettigar** [comment]
Please add GSSoC'24 label.

**Comment by Ijaiswalshivam** [comment]
@Vishwajith-Shettigar assigned

**Comment by Vishwajith-Shettigar** [comment]
> @Vishwajith-Shettigar assigned

Thank you.

**Comment by SharmaNishchay** [comment]
Added toast to show the timestamp when the message was sent.
Reference : #38
