### ISSUE TITLE
Bug: User is able to see main activity after logout

### ISSUE THREAD

**Issue by maniyaom** [Ijaiswalshivam/Talk-In#208]
Description:
Steps to reproduce:
1. Login with your credentials
2. Now go to profile screen and then click on logout
3. click on back button now you can see main activity
Here is the screen recording for the same:

https://github.com/Ijaiswalshivam/Talk-In/assets/105499099/803f707b-6627-4c87-8aa0-15cce07174d2

**Comment by Ashish-1020** [comment]
Pls assign me this I want to work on this ,I have experience of kotlin.
