### ISSUE TITLE
UI Enhancement

### ISSUE THREAD

**Issue by Ijaiswalshivam** [Ijaiswalshivam/Talk-In#21]
**Describe the solution you'd like**
Update UI/UX

**Comment by maniyaom** [comment]
assign me this issue

**Comment by NitinSigilipelli** [comment]
I am updating the UI/UX of this project from welcome screen to login and signup screens if possible i will update all screen

started working 
sample screenshots :
![fcedde78-ba8e-4ff1-b2a3-0e05d639e138](https://github.com/Ijaiswalshivam/Talk-In/assets/140246876/28f116d9-d31d-44da-b0e2-0dc9b1b07224)

Assign this issue to me @Ijaiswalshivam

**Comment by maniyaom** [comment]
I have made login and signup page already. we can do one thing once my code is updated you can add this screen because you have created new activity.

**Comment by NitinSigilipelli** [comment]
> I have made login and signup page already. we can do one thing once my code is updated you can add this screen because you have created new activity.

Actually he already assigned the issues regarding login , signup screens to me check it out once @maniyaom  
Thank you
