### ISSUE TITLE
Bug: Unverfied users are displayed on the mainactivity

### ISSUE THREAD

**Issue by maniyaom** [Ijaiswalshivam/Talk-In#211]
**Description:**
Other users can see unverified users and they can send messages to unverified user.

**Expected Behavior:**
Unverified users should not be displayed to other users.

**Screenshots:**
![talkin](https://github.com/Ijaiswalshivam/Talk-In/assets/105499099/23e1dc44-6404-41b2-b584-497ace1ae128)

**Comment by maniyaom** [comment]
I have fixed the issue but the problem is when users will sign in then only isVerified value on database will be added and all the verified user will be displayed. Should I push that code?

**Comment by javaman97** [comment]
> @Ijaiswalshivam @javaman97 I have fixed the issue but the problem is when users will sign in then only isVerified value on database will be added and all the verified user will be displayed. Should I push that code?

Go for it

**Comment by maniyaom** [comment]
@Ijaiswalshivam @javaman97 Someone is not using latest repositery for making changes. Previously i have implemented feature to update about me of the user that is removed.

**Comment by Ijaiswalshivam** [comment]
Ok.. I'll see it.. By the time you can push the assigned issues.

**Comment by maniyaom** [comment]
@Ijaiswalshivam I have opened a pull request for remove unverified users from mainactivity.
