### ISSUE TITLE
[DOC]: Adding thanks to contributors in readme.

### ISSUE THREAD

**Issue by rithika212k3** [Ijaiswalshivam/Talk-In#222]
**Description:**
Hi @Ijaiswalshivam,
I would like to add thanks to the contributor section and support section to the readme doc. **Can you please assign this issue to me?**

**Proposed Solution: **
A brief overview of the proposed solution.
-Adding the thanks to contributors' section with a beautiful image of all the contributors.

**Additional Context: **
Any additional context or relevant information.
**Screenshot** attached below 
![tnxs_support](https://github.com/Ijaiswalshivam/Talk-In/assets/158501895/f59006aa-57b2-45cc-8c77-bacaa6731c9e)

**Comment by Ijaiswalshivam** [comment]
@rithika212k3 assigned

**Comment by maniyaom** [comment]
@Ijaiswalshivam can you assign it to me? I have the solution

**Comment by rithika212k3** [comment]
Thank you for assigning me @Ijaiswalshivam 😊. Can you add the level label too?

**Comment by Ijaiswalshivam** [comment]
@rithika212k3 what's the progress?

**Comment by rithika212k3** [comment]
Almost done will send you the PR in few minutes.

**Comment by rithika212k3** [comment]
I have opened the PR. Can you please check that out @Ijaiswalshivam?
