### ISSUE TITLE
LogIn Verification through Email

### ISSUE THREAD

**Issue by Ijaiswalshivam** [Ijaiswalshivam/Talk-In#23]
Email Authentication

**Comment by Ijaiswalshivam** [comment]
@NitinSigilipelli Assigned

**Comment by NitinSigilipelli** [comment]
here it was shown as no one assigned please check it once @Ijaiswalshivam

**Comment by Ijaiswalshivam** [comment]
done

**Comment by NitinSigilipelli** [comment]
want anything else ?

**Comment by Ijaiswalshivam** [comment]
@NitinSigilipelli For the time being that will be good to go
