### ISSUE TITLE
Add Russian and Arabic language model in web app

### ISSUE THREAD

**Issue by SatwikMohan** [Ijaiswalshivam/Talk-In#237]
**Description:**
Add more languages in the multi language model

**Additional Context:**
I am a GSSOC'24 contributor and would like to work on the issue.

**Comment by SatwikMohan** [comment]
@Ijaiswalshivam May I go for other indian languages.

**Comment by Ijaiswalshivam** [comment]
@SatwikMohan for the time being it os not required.
And please share your dicord username, i have to discuss something.

**Comment by SatwikMohan** [comment]
@Ijaiswalshivam ok
username - satwikmohanagarwal
Display Name - Satwik Mohan | Contributor
email - satwikg17@gmail.com
