### ISSUE TITLE
SignUp Verification through Email

### ISSUE THREAD

**Issue by Ijaiswalshivam** [Ijaiswalshivam/Talk-In#24]
Email Authentication

**Comment by NitinSigilipelli** [comment]
hello @Ijaiswalshivam please assign this issue to me sir

**Comment by Vishwajith-Shettigar** [comment]
@Ijaiswalshivam can you please assign to me ?

**Comment by Ijaiswalshivam** [comment]
@NitinSigilipelli assigned

**Comment by Ijaiswalshivam** [comment]
@NitinSigilipelli  are you working on it?

**Comment by NitinSigilipelli** [comment]
yeah , i am working on both Ui and authentication through mail

**Comment by NitinSigilipelli** [comment]
@Ijaiswalshivam actually signup authentication code was not working it shows toast message as "please try again,Some error Occured" .So,few doubts i have 
1.i want to save username and email in firestore it may be usefull in future
2.sending email verification to user 
is it ok do now?

**Comment by Ijaiswalshivam** [comment]
Yes
