### ISSUE TITLE
Message Encryption in web app

### ISSUE THREAD

**Issue by SatwikMohan** [Ijaiswalshivam/Talk-In#245]
**Description:**
Encrypt text messages to ensure privacy and security.

**Problem:**
Messages are not encrypted so there is no privacy. Encrypted text messaging is a method of secure communication that converts your messages into code. 

**Additional Context:**
I am a GSSOC'24 contributor and would like to work on the issue.

**Comment by Ijaiswalshivam** [comment]
@SatwikMohan please see your discord.

**Comment by SatwikMohan** [comment]
@Ijaiswalshivam yes I have already message you
