### ISSUE TITLE
LogIn and SignUp through Mobile number with verification feature

### ISSUE THREAD

**Issue by Ijaiswalshivam** [Ijaiswalshivam/Talk-In#25]
create another interface asking for either login for email or mobile number

**Comment by NitinSigilipelli** [comment]
hello sir can i work on this issue under gssoc 24 .Kindly assign this to me sir

**Comment by NitinSigilipelli** [comment]
i am waiting for your reply @Ijaiswalshivam sir

**Comment by Ijaiswalshivam** [comment]
@NitinSigilipelli Assigned

**Comment by NitinSigilipelli** [comment]
thank you @Ijaiswalshivam

**Comment by maniyaom** [comment]
@Ijaiswalshivam can i work on this issue?

**Comment by Ijaiswalshivam** [comment]
@maniyaom assigned

**Comment by maniyaom** [comment]
@Ijaiswalshivam can you share me firebase project? so that i can setup mobile authentication?

**Comment by Ijaiswalshivam** [comment]
Share your mail id?

**Comment by maniyaom** [comment]
maniyaom592@gmail.com

**Comment by Ijaiswalshivam** [comment]
Done
