### ISSUE TITLE
Fix: Profile picture in chat activity & in main activity is not properly displayed

### ISSUE THREAD

**Issue by maniyaom** [Ijaiswalshivam/Talk-In#252]
When a user uploads an image with a small size, it gets messed up.
![IMG_20240601_184505](https://github.com/Ijaiswalshivam/Talk-In/assets/105499099/b82f7863-9d63-4189-a9bb-6d74b21257f2)
![Screenshot_2024-06-01-18-44-38-91_3c2d900447d6a97d9193ecf647571f72](https://github.com/Ijaiswalshivam/Talk-In/assets/105499099/4b3d6132-d0b1-4592-83dd-0a8fb64a39c6)

**Comment by Ijaiswalshivam** [comment]
@maniyaom assigned
