### ISSUE TITLE
Search bar modification

### ISSUE THREAD

**Issue by Ijaiswalshivam** [Ijaiswalshivam/Talk-In#263]

**Comment by maniyaom** [comment]
@Ijaiswalshivam assign me

**Comment by maniyaom** [comment]
@Ijaiswalshivam what modification do you need in search bar?

**Comment by Ijaiswalshivam** [comment]
![Screenshot_20240602-123023_GitHub.jpg](https://github.com/Ijaiswalshivam/Talk-In/assets/94839938/12248d17-187d-4f28-9170-0db2a31cb40f)
On top bar, search icon is present and when user clicks it then it expands to search, just like github one.
