### ISSUE TITLE
In mainactivity name is not showing properly

### ISSUE THREAD

**Issue by maniyaom** [Ijaiswalshivam/Talk-In#265]
If name is more than specific length then we have to compress it and add '...' at the end
![Screenshot_2024-06-02-12-38-19-57_3c2d900447d6a97d9193ecf647571f72](https://github.com/Ijaiswalshivam/Talk-In/assets/105499099/c613d118-8e36-4fff-99bc-fd7a61bfce50)

**Comment by javaman97** [comment]
@maniyaom  Do it after length of 25 letters

**Comment by maniyaom** [comment]
it is overlapping after 17 characters
