### ISSUE TITLE
Google authentication in android app

### ISSUE THREAD

**Issue by SatwikMohan** [Ijaiswalshivam/Talk-In#269]
**Description:**
All Authentication using google provider.

**Additional Context:**
I am a GSSOC'24 contributor and would like to work on the issue

**Comment by SatwikMohan** [comment]
The issue will allow user to Google SignIn in the android app. The app does not have the Google authentication functionality.

**Comment by Ijaiswalshivam** [comment]
@SatwikMohan remove facebook, twitter and yahoo icon and add only google and Microsoft for the Authentication.

**Comment by SatwikMohan** [comment]
@Ijaiswalshivam ok

**Comment by SatwikMohan** [comment]
implemented
