### ISSUE TITLE
Add progress bar while signing up and signing in and auto moving to Main APP after successful sign up

### ISSUE THREAD

**Issue by SatwikMohan** [Ijaiswalshivam/Talk-In#271]
**Additional Context:**
I am a GSSOC'24 contributor and would like to work on the issue

**Comment by maniyaom** [comment]
@Ijaiswalshivam it is already there.

**Comment by SatwikMohan** [comment]
Hello @maniyaom Here is the video as you can see as I pressed the sign up button nothing happens but in actual I got authenticated.

https://github.com/Ijaiswalshivam/Talk-In/assets/101632079/175a25f9-7f97-4f0a-9c84-55ad5e848298

@Ijaiswalshivam check the video

**Comment by SatwikMohan** [comment]
@Ijaiswalshivam I think so I updated it 2 hr ago

**Comment by SatwikMohan** [comment]
I'll check again

**Comment by Ijaiswalshivam** [comment]
If it happens again, will open this issue
