### ISSUE TITLE
Resolve Google Authentication error

### ISSUE THREAD

**Issue by SatwikMohan** [Ijaiswalshivam/Talk-In#274]
![Screenshot (482)](https://github.com/Ijaiswalshivam/Talk-In/assets/101632079/710ecaad-55f0-4b62-9727-ee8787e1945d)

**Additional Context:**
I am a GSSOC'24 contributor and would like to work on the isssue

**Comment by Ijaiswalshivam** [comment]
Hmm this is happening during sign up

**Comment by maniyaom** [comment]
@Ijaiswalshivam there is no issue please check it once

**Comment by maniyaom** [comment]
It is here
![image](https://github.com/Ijaiswalshivam/Talk-In/assets/105499099/4b423555-71d0-4db9-893d-1ce41f04beb9)
