### ISSUE TITLE
Enhance Readme

### ISSUE THREAD

**Issue by ananyag309** [Ijaiswalshivam/Talk-In#297]
Enhancing your README is crucial because it serves as the first point of contact for anyone interested in your project. A well-structured and detailed README can significantly improve the project's usability, attract contributors, and provide a clear understanding of the project's purpose and features.

I am willing to add more style, detailed to it. also i would like to add gssoc label to readme

**Comment by Ijaiswalshivam** [comment]
@ananyag309 assigned
