### ISSUE TITLE
debug some error

### ISSUE THREAD

**Issue by Ijaiswalshivam** [Ijaiswalshivam/Talk-In#30]
**Describe the bug**

C:/Users/ijais/.gradle/caches/transforms-4/4f0d8418c72cae040d9e187f194de809/transformed/play-services-measurement-api-22.0.0-api.jar!/META-INF/java.com.google.android.gmscore.integ.client.measurement_api_measurement_api.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.

**Expected behavior**
while building the app following error are occurring...while you can see in the image it is implemented correctly

**Screenshots**
Yes
![1](https://github.com/Ijaiswalshivam/Talk-In/assets/94839938/b3478b19-09a7-4847-ba02-d060f5829819)

**Comment by Vishwajith-Shettigar** [comment]
This can be resolved by changing    ` 'org.jetbrains.kotlin.android' version '1.7.10'`  to   `'org.jetbrains.kotlin.android' version '1.9.0`'

**Comment by Vishwajith-Shettigar** [comment]
Can you assign it to me ?

**Comment by Ijaiswalshivam** [comment]
@Vishwajith-Shettigar assigned
