### ISSUE TITLE
[BUG]: Default FirebaseApp is not initialized in this process com.example.talk_in.

### ISSUE THREAD

**Issue by Vishwajith-Shettigar** [Ijaiswalshivam/Talk-In#35]
**Describe the bug**
Unable to start activity ComponentInfo{com.example.talk_in/com.example.talk_in.LogIn}: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.example.talk_in.

**Expected behavior**
N/A

**Screenshots**

![image](https://github.com/Ijaiswalshivam/Talk-In/assets/76042077/066e3cf0-d41e-471d-98e0-06b2b9b7f8dc)

**Additional context**
N/A

**Comment by Vishwajith-Shettigar** [comment]
@Ijaiswalshivam please assign me.

**Comment by Ijaiswalshivam** [comment]
@Vishwajith-Shettigar assigned
