### ISSUE TITLE
Adding an Icon

### ISSUE THREAD

**Issue by Qomfortzone** [Ijaiswalshivam/Talk-In#44]
Hi Sir i would like to contribute to this project and this is my first issue i will design an icon and add to the app. Will add further issues and contribute to it.

**Comment by Qomfortzone** [comment]
Please 

> Hi Sir i would like to contribute to this project and this is my first issue i will design an icon and add to the app. Will add further issues and contribute to it.

Please assign this issue to me.

**Comment by Shirapti-nath** [comment]
PLease assign the label id like to work on this project under your supervision

**Comment by Ijaiswalshivam** [comment]
@Qomfortzone assigned

**Comment by Qomfortzone** [comment]
Completed Under #61
