### ISSUE TITLE
[BUG] MainActivity shows blank.

### ISSUE THREAD

**Issue by Vishwajith-Shettigar** [Ijaiswalshivam/Talk-In#50]
**Describe the bug**
MainActivity shows blank.

**Expected behavior**
Show users.

**Screenshots**

![image](https://github.com/Ijaiswalshivam/Talk-In/assets/76042077/c0222bf3-971e-4484-8c22-f81998d89745)

**Additional context**
N/A

**Comment by Ijaiswalshivam** [comment]
@Vishwajith-Shettigar assigned

**Comment by Vishwajith-Shettigar** [comment]
@Ijaiswalshivam, can you please check your firebase? I don't think its code fault.

**Comment by Ijaiswalshivam** [comment]
Yeah i was working initially, but now it is neither fetching nor storing the users data.

**Comment by hdhimalay** [comment]
sir, i am working on the pop up notifications, its almost ready, in the MainActvity it shows all the users. and by click on those users it will goto ChatActivity, kindly confirm that. initially mainAcivity shows blank but that hasbeen fixed, i will push this code by tonight

**Comment by Ijaiswalshivam** [comment]
@Vishwajith-Shettigar any update?
 or i should assign @hdhimalay ?, as he had resolved the issue.

**Comment by Vishwajith-Shettigar** [comment]
@Ijaiswalshivam assign him.

**Comment by Ijaiswalshivam** [comment]
@hdhimalay assigned

**Comment by Ijaiswalshivam** [comment]
@hdhimalay how much time will it take?

**Comment by hdhimalay** [comment]
@Ijaiswalshivam  CAN I CONNECT YOU THROUGH DISCORD NOW?, I HAVE TO DISCUSS SOMETHING RELATED TO POP NOTIFICATION.

**Comment by Ijaiswalshivam** [comment]
@hdhimalay yeah sure

**Comment by hdhimalay** [comment]
THIS LINK IS SHOWING BLANK , KINDLY himalaydas_36061 INVITE THIS USERNAME

**Comment by Vishwajith-Shettigar** [comment]
@Ijaiswalshivam, can you look at you firebase closely, i pretty much sure fault is not in code.

If your firebase project expired can you please create new one and update `google-services.json` file
