### ISSUE TITLE
Always asking for sign-in when app is reopened.

### ISSUE THREAD

**Issue by Ijaiswalshivam** [Ijaiswalshivam/Talk-In#54]
**Expected behavior**
when someone logged in to the app and again reopening it then it should be at main activity, 
and only if the user signed out then it should be asking for login credentials.

**Comment by maniyaom** [comment]
please assign this issue to me

**Comment by Ijaiswalshivam** [comment]
@maniyaom assigned

**Comment by Ijaiswalshivam** [comment]
@maniyaom after verifying I'll merge it... Please wait for some time.
