### ISSUE TITLE
Send Image 

### ISSUE THREAD

**Issue by Ijaiswalshivam** [Ijaiswalshivam/Talk-In#55]

**Comment by codebreaker3008** [comment]
@Ijaiswalshivam  could you assign this to me and explain a bit about it

**Comment by anshumanbehera27** [comment]
@Ijaiswalshivam Hey I am recently built the social media  platform  i have a similar kind of issue with my platform as well i would love to contribute to your project  it would be great if you assign this  issue to me

**Comment by anglerfishlyy** [comment]
I would like to upon this . will you assign me this issue for me ? 
Thank you.

**Comment by Ijaiswalshivam** [comment]
@codebreaker3008 assigned,
user can send and receive images
