### ISSUE TITLE
Send Videos

### ISSUE THREAD

**Issue by Ijaiswalshivam** [Ijaiswalshivam/Talk-In#56]

**Comment by shivam-sharma-2000** [comment]
I am a Gssoc24 Contributor. Can You Describe this issue? I think I can do it.

**Comment by Ijaiswalshivam** [comment]
Registered users can send and receive video.

**Comment by shivam-sharma-2000** [comment]
Please assign this issue to me.

**Comment by shivam-sharma-2000** [comment]
Do I have to use the fixissue branch only? Because I am not able to create a new branch.

**Comment by Ijaiswalshivam** [comment]
no, it's not necessary

**Comment by shivam-sharma-2000** [comment]
Sure, thanks for assigning the issue to me,

However, I am not able to create a new branch or push my local branch in the repo. Can you please assign the required permissions to me?

**Comment by Ijaiswalshivam** [comment]
here, from my side everything is good.

**Comment by Ijaiswalshivam** [comment]
@shivam-sharma-2000 now everything is good, you can start contributing on this project

**Comment by varshithar12** [comment]
I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue.
