### ISSUE TITLE
[DOC] : UPDATING feature_request.md template

### ISSUE THREAD

**Issue by anglerfishlyy** [Ijaiswalshivam/Talk-In#68]
**Describe the bug**
feature_request template is precise but not COMPLETE.

**Expected behavior**
contributors should have a complete detailed template which makes them easy to create an issue.

**Additional context**
Updating templates is necessary for clarity in the minds of contributors.while opening an issue they themselves get the whole idea about the issue they are trying to create , resulting in a much better issue for our project.

lets collectively make our TALK-IN shine with our efforts.....!!

**Comment by anglerfishlyy** [comment]
Is this okay? can you guys assign me this?

**Comment by Ijaiswalshivam** [comment]
@anglerfishlyy assigned

**Comment by anglerfishlyy** [comment]
Hello sir , can you please tell me how to use this app ? where is it available ?
