### ISSUE TITLE
Login button bug fix

### ISSUE THREAD

**Issue by Ijaiswalshivam** [Ijaiswalshivam/Talk-In#7]
As first page of app is login page so when login button is pressed then the application shuts down, so you can fix this issue.

**Comment by Shreesammat** [comment]
i would like to work on this issue

**Comment by Qomfortzone** [comment]
Under GSSoC24 I would like to fix the issue.

**Comment by Ijaiswalshivam** [comment]
> i would like to work on this issue under #GSSoC24

@Shreesammat Currently some files are missing, currently I'm assigning you if you can fix the issue then great, otherwise within few days you will get all the files then you can contribute there, I hope you'll understand it.

**Comment by Aditya19110** [comment]
Hey i would like to contribute in the same feature..

**Comment by Shreesammat** [comment]
> > i would like to work on this issue under #GSSoC24
> 
> @Shreesammat Currently some files are missing, currently I'm assigning you if you can fix the issue then great, otherwise within few days you will get all the files then you can contribute there, I hope you'll understand it.
yes that would be great @Ijaiswalshivam.

**Comment by Ijaiswalshivam** [comment]
@Shreesammat All files are restored now you can fix the issue.

**Comment by Shreesammat** [comment]
> @Shreesammat All files are restored now you can fix the issue.


 Ok @Ijaiswalshivam. Will start doing immediately.

**Comment by AdityaPrakash-03** [comment]
i will like to work on the issue, please assign it to me
