### ISSUE TITLE
[DOC] : Creating PULL REQUEST TEMPLATE.

### ISSUE THREAD

**Issue by anglerfishlyy** [Ijaiswalshivam/Talk-In#72]
**PROBLEM**
There is no template designed for PULL REQUEST from your side .

**Describing the solution i like**
I Will design a proper , concise Pull Request Template .

**Advantages of my solution**
 1.Better understanding of Pull Requests by the viewers.
2.Template allows contributors ponder less over thinking how should he/she write PR.
3. Saves contributor and viewer time alike.

Lets make TALK-IN app good!!

**Comment by anglerfishlyy** [comment]
can you assign me this?

**Comment by anglerfishlyy** [comment]
anyways , I am gonna start working on this and will create PR regarding this.
Do check it out when time permits .
Thank you.

**Comment by Ijaiswalshivam** [comment]
@anglerfishlyy merged
