### ISSUE TITLE
Top Bar Color #GSSOC'24

### ISSUE THREAD

**Issue by Lucky-chelani** [Ijaiswalshivam/Talk-In#74]
I would like to change the top app bar color  under GGSOC"24

**Comment by Ijaiswalshivam** [comment]
@Lucky-chelani assigned

**Comment by Lucky-chelani** [comment]
Done

**Comment by varshithar12** [comment]
I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue.
