### ISSUE TITLE
Desiginig and Code of the top bar of the Main Activity 

### ISSUE THREAD

**Issue by Qomfortzone** [Ijaiswalshivam/Talk-In#78]
@Ijaiswalshivam 
Adding the top bar to the homepage of the app.(Main Activity)
Assign this to me.

**Comment by Qomfortzone** [comment]
I am working on the complete design of the main activity ....Will add more pull requests.

**Comment by Ijaiswalshivam** [comment]
@Qomfortzone assigned

**Comment by Qomfortzone** [comment]
Done Under #81
