### ISSUE TITLE
Update ReadMe.md file

### ISSUE THREAD

**Issue by Ijaiswalshivam** [Ijaiswalshivam/Talk-In#8]

**Comment by SharmaNishchay** [comment]
made a PR of updated README.md, if any changes are required kindly convey them.

**Comment by AdityaPrakash-03** [comment]
i would like to do  the changes here and make it more  understandable for others to contribute to it, please assign it

**Comment by Qomfortzone** [comment]
Please Assign the Issue.

**Comment by Ijaiswalshivam** [comment]
> i would like to do the changes here and make it more understandable for others to contribute to it, please assign it
 @AdityaPrakash-03 Assigned

**Comment by SharmaNishchay** [comment]
@Ijaiswalshivam are we planning to add a license? If, yes then which one?

**Comment by X-Cypher** [comment]
Hi, i am interested to contribute. Can you assign this issue to me

**Comment by Ijaiswalshivam** [comment]
@SharmaNishchay Assigned, and as per your knowledge, you can add it.

**Comment by Ijaiswalshivam** [comment]
@AdityaPrakash-03 assigned

**Comment by AdityaPrakash-03** [comment]
@Ijaiswalshivam anything more to be added, let me know I will add.

**Comment by Ijaiswalshivam** [comment]
It's looking good
