### ISSUE TITLE
Missing Description

### ISSUE THREAD

**Issue by Faiz-Shaikh-16** [Ijaiswalshivam/Talk-In#80]
The description of the project is missing. Can u assign it to me so that i can help..

**Comment by Faiz-Shaikh-16** [comment]
@Ijaiswalshivam Hey, I am done with the description part, can u tell me how to pull request?

**Comment by Ijaiswalshivam** [comment]
@Faiz-Shaikh-16 you can create pull request from your github window after committing all the files through git
