### ISSUE TITLE
Login button

### ISSUE THREAD

**Issue by Ijaiswalshivam** [Ijaiswalshivam/Talk-In#82]
**Description:**
when app is in dark mode then login button is working but if turned to light mode then app shuts down.

**Comment by maniyaom** [comment]
@Ijaiswalshivam please assign me i found solution

**Comment by Ijaiswalshivam** [comment]
@maniyaom what about previous pr?

**Comment by maniyaom** [comment]
i am not able to open sign in page due to this issue and that merge conflict was occuring because complete ui was changed by you i am fixing it

**Comment by Ijaiswalshivam** [comment]
@maniyaom assigned

**Comment by maniyaom** [comment]
assign level

**Comment by varshithar12** [comment]
https://lnkd.in/dQzT_UHE

**Comment by varshithar12** [comment]
I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue.
