### ISSUE TITLE
Add Create Group feature 

### ISSUE THREAD

**Issue by Ijaiswalshivam** [Ijaiswalshivam/Talk-In#9]
This add group feature will create group of users so that they can convey their message to members of group on a single text.

**Comment by Varun-Sethi-Dev** [comment]
Hey I owuld like to work on this feature would you assign this to me #gssoc2024

**Comment by Aditya19110** [comment]
I would like to Work on this issue i have also created a Same function in my app so i can also work on the same #6

**Comment by hdhimalay** [comment]
Sir, i want to work on this features, kindly assign this to me. #GSSoc2024

**Comment by Ajay-patidar0** [comment]
Hello sir, I want to work on this feature, Please assign this issue to me. Also add the level for GSSoc2024. #6

**Comment by NitinSigilipelli** [comment]
Hello sir,I have an experience of more than year in android development  please check my profile and kindly assign this work to me

**Comment by Ijaiswalshivam** [comment]
@NitinSigilipelli assigned

**Comment by Ijaiswalshivam** [comment]
@Varun-Sethi-Dev assigned

**Comment by javaman97** [comment]
@Varun-Sethi-Dev What's the progress?

**Comment by Varun-Sethi-Dev** [comment]
> @Varun-Sethi-Dev What's the progress?

just need some time my sem exams are starting from today

**Comment by Ijaiswalshivam** [comment]
@Varun-Sethi-Dev 
Given your ongoing examinations, I understand the challenge of managing your responsibilities. However, as this issue requires prompt attention and cannot be postponed indefinitely, I am reassigning it to others. Please ensure that it is addressed promptly.

**Comment by Varun-Sethi-Dev** [comment]
> @Varun-Sethi-Dev 
> Given your ongoing examinations, I understand the challenge of managing your responsibilities. However, as this issue requires prompt attention and cannot be postponed indefinitely, I am reassigning it to others. Please ensure that it is addressed promptly.

I understand the urgency of this feature so you may re assign it to some one else I will work on another Issue asap after exams

**Comment by Ijaiswalshivam** [comment]
@Varun-Sethi-Dev Great

**Comment by Qomfortzone** [comment]
@Ijaiswalshivam 
Assign me
