### ISSUE TITLE
Filter genuine email

### ISSUE THREAD

**Issue by pankaj-bind** [Ijaiswalshivam/Talk-In#91]
**Description:**
In your application anyone can enter using **temporary or disposable email**.
I will add a feature so that no one could create an account using **temporary or disposable email**.

**Problem:**
It will allow only genuine users in your database.
It will help to avoid any bot.

**Proposed Solution:**
I'll implement a feature so that no can use such type of emails for register and login.

**Additional Context:**
Assign me this work under GSSoC24, I will implement it.

**Comment by Ijaiswalshivam** [comment]
Hello @pankaj-bind, currently sign-in and signup authentication is under development,
but yes, we can add the above proposed issue as an additional feature.
so, I'm assigning you.

**Comment by pankaj-bind** [comment]
> Hello @pankaj-bind, currently sign-in and signup authentication is under development, but yes, we can add the above proposed issue as an additional feature. so, I'm assigning you.

I will use an API which is free it will first checks is the email genuine or not, if yes then it proceeds otherwise, breaks operation and shows a popup "invalid email"
I have tried this, and this feature is very unique.

**Comment by Ijaiswalshivam** [comment]
@pankaj-bind assigned

**Comment by javaman97** [comment]
@pankaj-bind Let us know more about the API in detail to help others
