### ISSUE TITLE
During Sign-Up with new mail id's, always giving pop up "The email address is already in use by another account"

### ISSUE THREAD

**Issue by Ijaiswalshivam** [Ijaiswalshivam/Talk-In#95]

**Comment by Ijaiswalshivam** [comment]
@NitinSigilipelli assiging you

**Comment by NitinSigilipelli** [comment]
@Ijaiswalshivam ok but i am not getting like that when i use new email to signup it gives me toast msg as "verfication mail sent" and redirects to login page check it once may be you using already existed mail

**Comment by Ijaiswalshivam** [comment]
@NitinSigilipelli already tried but same response.

**Comment by NitinSigilipelli** [comment]
@Ijaiswalshivam while signup wait until you get both toast msgs "Registration sucessfull" and "verification mail sent" then it automatically redirects to login page once check now i deleted mail from authentication

**Comment by Ijaiswalshivam** [comment]
Ohk..got it recently i changed the json file

**Comment by NitinSigilipelli** [comment]
@Ijaiswalshivam ok 👍

**Comment by Ijaiswalshivam** [comment]
@NitinSigilipelli I have attached json file in "imp files" kindly checkout why this is happening and please try, not to change the .json file as everyone having error with changing in there file...so lets stick with one.

**Comment by NitinSigilipelli** [comment]
hii @Ijaiswalshivam is this issue solved ?

**Comment by Ijaiswalshivam** [comment]
@NitinSigilipelli yes it is fixed only the problem is that when I'm signing in then it is sending mail instead of at time sign up
